# Generated by Django 5.0.6 on 2024-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_payment_session_id_alter_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="way",
            field=models.CharField(
                choices=[("наличные", "наличные"), ("перевод", "перевод")],
                default="перевод",
                max_length=15,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
