# Generated by Django 5.0.6 on 2024-06-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата создания платежа"
            ),
        ),
    ]
