# Generated by Django 5.0.6 on 2024-06-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="стоимость курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="стоимость урока",
            ),
        ),
    ]
