# Generated by Django 5.0.6 on 2024-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0005_course_price_lesson_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="video",
            new_name="url",
        ),
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последнего обновления"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="last_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
